# Generated by Django 4.2.23 on 2025-08-11 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requerimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('material', 'Material Didático'), ('equipamento', 'Equipamento'), ('reforma', 'Reforma'), ('evento', 'Evento'), ('outro', 'Outro')], max_length=20, verbose_name='Tipo')),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=20, verbose_name='Prioridade')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_analise', 'Em Análise'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado'), ('concluido', 'Concluído')], default='pendente', max_length=20, verbose_name='Status')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Solicitação')),
                ('data_resposta', models.DateTimeField(blank=True, null=True, verbose_name='Data de Resposta')),
                ('resposta', models.TextField(blank=True, verbose_name='Resposta')),
                ('administrador_resposta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Administrador que Respondeu')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professores.professor', verbose_name='Professor')),
            ],
            options={
                'verbose_name': 'Requerimento',
                'verbose_name_plural': 'Requerimentos',
                'ordering': ['-data_solicitacao'],
            },
        ),
        migrations.CreateModel(
            name='LogSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('tipo', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('criacao', 'Criação'), ('edicao', 'Edição'), ('exclusao', 'Exclusão'), ('visualizacao', 'Visualização'), ('erro', 'Erro')], max_length=20, verbose_name='Tipo')),
                ('acao', models.CharField(max_length=200, verbose_name='Ação')),
                ('detalhes', models.TextField(blank=True, verbose_name='Detalhes')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Endereço IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log do Sistema',
                'verbose_name_plural': 'Logs do Sistema',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('ano_letivo_atual', models.IntegerField(verbose_name='Ano Letivo Atual')),
                ('periodo_inscricao_aberto', models.BooleanField(default=False, verbose_name='Período de Inscrição Aberto')),
                ('data_inicio_ano_letivo', models.DateField(verbose_name='Data de Início do Ano Letivo')),
                ('data_fim_ano_letivo', models.DateField(verbose_name='Data de Fim do Ano Letivo')),
                ('max_alunos_por_turma', models.IntegerField(default=40, verbose_name='Máximo de Alunos por Turma')),
                ('nota_minima_aprovacao', models.DecimalField(decimal_places=1, default=6.0, max_digits=3, verbose_name='Nota Mínima para Aprovação')),
                ('unidade_escolar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.unidadeescolar', verbose_name='Unidade Escolar')),
            ],
            options={
                'verbose_name': 'Configuração do Sistema',
                'verbose_name_plural': 'Configurações do Sistema',
            },
        ),
    ]
