# Generated by Django 4.2.23 on 2025-08-11 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('matricula', models.CharField(max_length=20, unique=True, verbose_name='Matrícula')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, verbose_name='Sexo')),
                ('endereco', models.TextField(verbose_name='Endereço')),
                ('nome_responsavel', models.CharField(max_length=200, verbose_name='Nome do Responsável')),
                ('telefone_responsavel', models.CharField(max_length=20, verbose_name='Telefone do Responsável')),
                ('email_responsavel', models.EmailField(blank=True, max_length=254, verbose_name='E-mail do Responsável')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('transferido', 'Transferido'), ('concluido', 'Concluído')], default='ativo', max_length=20, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
                'ordering': ['usuario__first_name', 'usuario__last_name'],
            },
        ),
        migrations.CreateModel(
            name='AlunoTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('data_entrada', models.DateField(auto_now_add=True, verbose_name='Data de Entrada')),
                ('data_saida', models.DateField(blank=True, null=True, verbose_name='Data de Saída')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Aluno na Turma',
                'verbose_name_plural': 'Alunos nas Turmas',
            },
        ),
        migrations.CreateModel(
            name='EntregaTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('arquivo', models.FileField(upload_to='trabalhos/', verbose_name='Arquivo')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nota')),
                ('data_entrega', models.DateTimeField(auto_now_add=True, verbose_name='Data de Entrega')),
            ],
            options={
                'verbose_name': 'Entrega de Trabalho',
                'verbose_name_plural': 'Entregas de Trabalhos',
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('tipo', models.CharField(choices=[('prova1', 'Prova 1'), ('prova2', 'Prova 2'), ('prova3', 'Prova 3'), ('prova4', 'Prova 4'), ('recuperacao', 'Recuperação'), ('trabalho', 'Trabalho'), ('participacao', 'Participação'), ('outro', 'Outro')], max_length=20, verbose_name='Tipo')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor')),
                ('data_avaliacao', models.DateField(verbose_name='Data da Avaliação')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
                'ordering': ['-data_avaliacao'],
            },
        ),
        migrations.CreateModel(
            name='Trabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('individual', 'Individual'), ('grupo', 'Grupo'), ('projeto', 'Projeto'), ('pesquisa', 'Pesquisa')], max_length=20, verbose_name='Tipo')),
                ('data_entrega', models.DateField(verbose_name='Data de Entrega')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor (pontos)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Trabalho',
                'verbose_name_plural': 'Trabalhos',
                'ordering': ['-data_entrega'],
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Turma')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('turno', models.CharField(choices=[('manha', 'Manhã'), ('tarde', 'Tarde'), ('noite', 'Noite'), ('integral', 'Integral')], max_length=20, verbose_name='Turno')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('unidade_escolar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.unidadeescolar', verbose_name='Unidade Escolar')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'ordering': ['ano', 'nome'],
            },
        ),
    ]
