# Generated by Django 4.2.23 on 2025-08-11 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('professores', '0001_initial'),
        ('accounts', '0001_initial'),
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabalho',
            name='turma_disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professores.turmadisciplina', verbose_name='Turma/Disciplina'),
        ),
        migrations.AddField(
            model_name='nota',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.aluno', verbose_name='Aluno'),
        ),
        migrations.AddField(
            model_name='nota',
            name='turma_disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professores.turmadisciplina', verbose_name='Turma/Disciplina'),
        ),
        migrations.AddField(
            model_name='entregatrabalho',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.aluno', verbose_name='Aluno'),
        ),
        migrations.AddField(
            model_name='entregatrabalho',
            name='trabalho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.trabalho', verbose_name='Trabalho'),
        ),
        migrations.AddField(
            model_name='alunoturma',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.aluno', verbose_name='Aluno'),
        ),
        migrations.AddField(
            model_name='alunoturma',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.turma', verbose_name='Turma'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='unidade_escolar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.unidadeescolar', verbose_name='Unidade Escolar'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterUniqueTogether(
            name='turma',
            unique_together={('nome', 'unidade_escolar', 'ano')},
        ),
        migrations.AlterUniqueTogether(
            name='nota',
            unique_together={('aluno', 'turma_disciplina', 'tipo')},
        ),
        migrations.AlterUniqueTogether(
            name='entregatrabalho',
            unique_together={('trabalho', 'aluno')},
        ),
        migrations.AlterUniqueTogether(
            name='alunoturma',
            unique_together={('aluno', 'turma')},
        ),
    ]
